ALTER TABLE "Entreprise"
  ADD COLUMN IF NOT EXISTS "logoUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "themeColor" VARCHAR(7) NOT NULL DEFAULT '#0f6fcb',
  ADD COLUMN IF NOT EXISTS "description" VARCHAR(120);
